apiVersion: apps/v1
kind: Deployment
metadata:
  name: warweb-deployment
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: warweb-container
        image: subhashrokkala/war-web-project:latest
        ports:
        - containerPort: 8080
